sample_site/api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path(
        'v1/categories/',
        views.api_categories,
        name='api-categories'
    ),
    path(
        'v1/category/<int:pk>/',
        views.api_category_detail,
        name='api-category-detail'
    ),
    path(
        'v1/billboards/',
        views.api_billboards,
        name='api-billboards',
    ),
    path(
        'v1/billboard/<int:pk>/',
        views.api_billboard_detail,
        name='api-billboard-detail',
    ),
    path(
        'v1/comments/',
        views.api_comments,
        name='api-comments',
    ),
    path(
        'v1/users/',
        views.api_users,
        name='api-users',
    ),
    path(
        'v1/user/<int:pk>/',
        views.api_user,
        name='api-user',
    )
]

sample_site/billboard/urls.py
from django.urls import path

from . import views

app_name = 'billboard'

urlpatterns = [
    path(
        '',
        views.search_form_function,
        name='index',
    ),
    path(
        'boards/<int:pk>/',
        views.BillBoardDetailView.as_view(),
        name='billboard_detail',
    ),
    path(
        'boards/<slug:category_name>/',
        views.CategoryListView.as_view(),
        name='category_bbs',
    ),
    path(
        'board/create/',
        views.BillBoardCreateView.as_view(),
        name='create_billboard',
    ),
    path(
        'board/<int:pk>/edit/',
        views.BillBoardUpdateView.as_view(),
        name='update_billboard',
    ),
    path(
        'board/<int:pk>/delete/',
        views.BillBoardDeleteView.as_view(),
        name='delete_billboard',
    ),
    path(
        'board/<int:pk>/comments/create/',
        views.CommentCreate.as_view(),
        name='create_comment',
    ),
    path(
        'board/<int:pk>/edit_comment/<int:comment_id>/',
        views.CommentUpdate.as_view(),
        name='update_comment',
    ),
    path(
        'board/<int:pk>/delete_comment/<int:comment_id>/',
        views.CommentDelete.as_view(),
        name='delete_comment',
    ),
    path(
        'profile/<slug:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'profile/<slug:username>/edit/',
        views.UserCreateView.as_view(),
        name='edit_profile',
    )
]

sample_site/pages/urls.py
from .views import About, Rules
from django.urls import path


app_name = 'pages'

urlpatterns = [
    path('rules/', Rules.as_view(), name='rules'),
    path('about/', About.as_view(), name='about'),
]

sample_site/sample_site/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView


urlpatterns = [
    path('pages/', include('pages.urls')),
    path('', include('billboard.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('billboard:index'),
        ),
        name='registration',
    ),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sample_site/templates/includes/billboard_card.html
<div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        <h2>{{ billboard.title }}</h2>
        <p>Автор: <a href="{% url "billboard:profile" billboard.author.username %}">@{{ billboard.author.username }}</a></p>
        <p>Категория: <a href="{% url 'billboard:category_bbs' billboard.category.slug %}">{{ billboard.category.title }}</a>
        </p>
        <p>Опубликовано: {{ billboard.published_at|date:"d.m.Y H:i:s" }}</p>
        <p>Цена: {{ billboard.price }} руб.</p>
        <a href="{% url "billboard:billboard_detail" billboard.id %}">Подробнее</a>
      </div>
    </div>
  </div>

sample_site/templates/includes/comments.html
{% block content %}
<div>
  <p>
    <b>Комментарии ({{ billboard.comment_count }})</b>
  </p>
</div>
<form method="post" action="{% url 'billboard:create_comment' billboard.id %}">
  {% csrf_token %}
  <table>
    {{ form }}
  </table>
  <input type="submit" value="Добавить" />
</form>
<hr />
{% for comment in comments %}
<div>
  <p><b>Комментарий {{ comment.id }}:</b></p>
  <p> Автор: <a href="{% url "billboard:profile" comment.author %}" >@{{ comment.author }}</a></p>
  <p> Текст комментария: {{ comment.text }}</p>
  <p> Опубликован: {{ comment.created_at|date:"d.m.Y" }}</p>
  {% if user == comment.author %}
  <a href="{% url "billboard:update_comment" comment.billboard_id comment.id %}">Отредактировать комментарий</a>
  <a href="{% url "billboard:delete_comment" comment.billboard_id comment.id %}">Удалить комментарий</a>
  {% endif %}
</div>
  {% endfor %} {% endblock content %}

sample_site/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Биллбордс</p>
</footer>

sample_site/templates/includes/header.html
{% load django_bootstrap5 %}

<nav >
    <a href="{% url "billboard:index" %}">
        Главная
    </a>
    {% for category in categories %}
    <a href="{% url "billboard:category_bbs" category.slug %}">
        {{ category.title }}
    </a>
    {% endfor %}
    <a href="{% url "pages:rules" %}">
        Правила использования сайта
    </a>
    <a href="{% url "pages:about" %}">
        О сайте
    </a>
    {% if user.is_authenticated %}
    <a href="{% url "billboard:create_billboard" %}">
        Добавить объявление
    </a>
    <a href="{% url "billboard:profile" user.username %}">
        {{ user.username }}
    </a>
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}    
        {% bootstrap_button 'Выйти' %}
    </form>
    {% else %}
    <a href="{% url "login" %}">
        Войти
    </a>
    <a href="{% url "registration" %}">
        Регистрация
    </a>
    {% endif %}
</nav>

sample_site/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}