sample_site/api/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path(
        'v1/categories/',
        views.api_categories,
        name='api-categories'
    ),
    path(
        'v1/category/<int:pk>/',
        views.api_category_detail,
        name='api-category-detail'
    ),
    path(
        'v1/billboards/',
        views.api_billboards,
        name='api-billboards',
    ),
    path(
        'v1/billboard/<int:pk>/',
        views.api_billboard_detail,
        name='api-billboard-detail',
    ),
    path(
        'v1/comments/',
        views.api_comments,
        name='api-comments',
    ),
    path(
        'v1/users/',
        views.api_users,
        name='api-users',
    ),
    path(
        'v1/user/<int:pk>/',
        views.api_user,
        name='api-user',
    )
]

sample_site/billboard/urls.py
from django.urls import path

from . import views

app_name = 'billboard'

urlpatterns = [
    path(
        '',
        views.search_form_function,
        name='index',
    ),
    path(
        'boards/<int:pk>/',
        views.BillBoardDetailView.as_view(),
        name='billboard_detail',
    ),
    path(
        'boards/<slug:category_name>/',
        views.CategoryListView.as_view(),
        name='category_bbs',
    ),
    path(
        'board/create/',
        views.BillBoardCreateView.as_view(),
        name='create_billboard',
    ),
    path(
        'board/<int:pk>/edit/',
        views.BillBoardUpdateView.as_view(),
        name='update_billboard',
    ),
    path(
        'board/<int:pk>/delete/',
        views.BillBoardDeleteView.as_view(),
        name='delete_billboard',
    ),
    path(
        'board/<int:pk>/comments/create/',
        views.CommentCreate.as_view(),
        name='create_comment',
    ),
    path(
        'board/<int:pk>/edit_comment/<int:comment_id>/',
        views.CommentUpdate.as_view(),
        name='update_comment',
    ),
    path(
        'board/<int:pk>/delete_comment/<int:comment_id>/',
        views.CommentDelete.as_view(),
        name='delete_comment',
    ),
    path(
        'profile/<slug:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'profile/<slug:username>/edit/',
        views.UserCreateView.as_view(),
        name='edit_profile',
    )
]

sample_site/sample_site/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView


urlpatterns = [
    path('pages/', include('pages.urls')),
    path('', include('billboard.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('billboard:index'),
        ),
        name='registration',
    ),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sample_site/billboard/models.py
from django.db import models
from django.core import validators
from django.contrib.auth import get_user_model
import uuid

from .validators import validate_price, validate_title


User = get_user_model()


class Category(models.Model):
    title = models.CharField(
        max_length=25,
        unique=True,
        verbose_name='Заголовок'
    )
    slug = models.SlugField(
        unique=True,
        blank=False,
        verbose_name='Идентификатор',
    )
    description = models.TextField(
        verbose_name='Описание категории',
    )

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['slug']

    def __str__(self):
        return self.title


class Purchase(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    buyer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        verbose_name='Покупатель',
        related_name='buyer',
    )
    item_name = models.CharField(
        max_length=50,
        verbose_name='Объявление',
    )
    salesman = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        verbose_name='Продавец',
        related_name='salesman',
    )
    cost = models.FloatField(
        verbose_name='Цена',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Сделка оформлена',
    )


class BillBoard(models.Model):

    class Kinds(models.IntegerChoices):
        BUY = 1, 'Покупка'
        SELL = 2, 'Продажа'
        EXCHANGE = 3, 'Обмен'
        RENT = 4, 'Аренда'
        __empty__ = 'Выберите тип публикуемого объявления'

    title = models.CharField(
        max_length=50,
        verbose_name='Объявление',
        validators=[validate_title],
    )
    unique_bb_id = models.UUIDField(
        primary_key=False,
        default=uuid.uuid4,
        editable=False,
    )
    content = models.TextField(
        verbose_name='Описание',
        blank=False,
    )
    price = models.FloatField(
        verbose_name='Цена',
        validators=[validate_price],
    )
    published_at = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Опубликовано'
    )
    category = models.ForeignKey(
        Category,
        null=True,
        on_delete=models.PROTECT,
        verbose_name='Категория',
    )
    kind = models.SmallIntegerField(
        choices=Kinds.choices,
        default=Kinds.__empty__,
        verbose_name='Тип сделки',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        verbose_name='Автор объявления',
    )
    image = models.ImageField(
        blank=True,
        default='images/billboard.jpg',
        verbose_name='Изображение',
        upload_to='images/%Y/%m/%d/',
        validators=[
            validators.FileExtensionValidator(
                allowed_extensions=('jpg', 'png', 'jpeg',)
            )
        ],
        error_messages={
            'invalid_extension': 'Этот формат не поддерживается'
        }
    )

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['category__slug', '-published_at']


class Comment(models.Model):
    billboard = models.ForeignKey(
        BillBoard,
        related_name='comments',
        on_delete=models.CASCADE,
    )
    text = models.TextField(
        blank=False,
        verbose_name='Текст комментария',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False,
        verbose_name='Автор комментария',
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created_at',)

    def __str__(self):
        return f'{self.text}'

sample_site/billboard/forms.py
from django import forms
from django.contrib.auth import get_user_model
from captcha.fields import CaptchaField

from .models import (
    BillBoard,
    Comment,
    Category,
)

User = get_user_model()


class BillBoardForm(forms.ModelForm):
    captcha = CaptchaField(
        label='Введите текст с картинки',
        error_messages={
            'invalid': 'Неправильный текст',
        },
        generator='captcha.helpers.random_char_challenge',
    )

    class Meta:
        model = BillBoard
        fields = ('title', 'content', 'price', 'image', 'category', 'kind',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class BillBoardSearchForm(forms.Form):
    field_order = ('')
    billboard_category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        label='Категория товара',
    )
    billboard_kind = forms.ChoiceField(
        choices=BillBoard.Kinds.choices,
        label='Тип сделки',
    )
    price_min = forms.FloatField(
        label='Мин. цена',
    )
    price_max = forms.FloatField(
        label='Макс. цена',
    )


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
        )

sample_site/billboard/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.conf import settings
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import HttpRequest, HttpResponse

from .models import (
    BillBoard,
    Category,
    Comment,
    User,
)
from .forms import (
    BillBoardForm,
    CommentForm,
    BillBoardSearchForm,
    UserForm,
)


def search_form_function(request: HttpRequest) -> HttpResponse:
    categories = Category.objects.all()
    context = {
        'categories': categories,
    }
    if request.method == 'POST':
        search_form = BillBoardSearchForm(request.POST)
        if search_form.is_valid():
            bb_category = search_form.cleaned_data['billboard_category']
            price_min = search_form.cleaned_data['price_min']
            price_max = search_form.cleaned_data['price_max']
            bb_kind = search_form.cleaned_data['billboard_kind']
            category = Category.objects.get(
                title=bb_category,
            )
            billboards = BillBoard.objects.filter(
                price__range=(price_min, price_max),
                category__slug__exact=category.slug,
                kind__exact=bb_kind,
            )
            categories = Category.objects.all()
            paginator = Paginator(
                billboards,
                settings.PAGINATE_NUMBER,
            )
            page_number = request.GET.get('page')
            page_obj = paginator.get_page(page_number)
            context['page_obj'] = page_obj
            context['form'] = search_form
            return render(
                request,
                'billboard/index.html',
                context,
            )
    else:
        billboards = BillBoard.objects.all()
        search_form = BillBoardSearchForm()
        paginator = Paginator(
            billboards,
            settings.PAGINATE_NUMBER,
        )
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        context['form'] = search_form
    return render(
        request,
        'billboard/index.html',
        context,
    )


def profile(request: HttpRequest, username):
    user = get_object_or_404(
        User,
        username=username,
    )

    categories = Category.objects.all()

    billboards = BillBoard.objects.filter(
        author=user
    )

    context = {
        'profile': user,
        'categories': categories,
        'billboards': billboards,
    }

    return render(
        request,
        'billboard/profile.html',
        context
    )


class CategoryListView(ListView):
    paginate_by = 2
    template_name = 'billboard/category.html'

    def get_queryset(self):
        return BillBoard.objects.filter(
            category__slug__exact=self.kwargs['category_name']
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['category'] = Category.objects.get(
            slug=self.kwargs['category_name']
        )
        return context


class BillBoardDetailView(DetailView):
    template_name = 'billboard/detail.html'
    model = BillBoard

    def get_queryset(self):
        billboards = BillBoard.objects.annotate(
            comment_count=Count('comments'),
        )
        return billboards

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        form = CommentForm()
        context['form'] = form
        comments = Comment.objects.filter(
            billboard__exact=self.kwargs['pk']
        )
        context['comments'] = comments
        return context


class BillBoardCreateView(CreateView):
    template_name = 'billboard/create.html'
    form_class = BillBoardForm
    success_url = reverse_lazy('billboard:index')
    initial = {
        'price': 0.0,
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.save()
        title = form.cleaned_data['title']
        send_mail(
            subject='Создание объявления',
            message=f'Вы создали объявление "{title}"!',
            recipient_list=[f'{title}@sample_site.ru'],
            from_email='publish_billboard@sample_site.ru'
        )
        return super().form_valid(form)


class BillBoardUpdateView(UpdateView):
    model = BillBoard
    template_name = 'billboard/create.html'
    form_class = BillBoardForm
    success_url = reverse_lazy('billboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class BillBoardDeleteView(DeleteView):
    model = BillBoard
    template_name = 'billboard/create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['billboard'] = BillBoard.objects.get(
            pk=self.kwargs['pk'],
        )
        return context

    def get_success_url(self):
        return reverse_lazy(
            'billboard:index',
        )


class UserCreateView(UpdateView):
    model = User
    template_name = 'billboard/user.html'

    def get_object(self, queryset=User.objects.all()):
        username = self.kwargs['username']
        user = User.objects.get(
            username=username,
        )
        return user

    def get_form(self, form_class=User):
        instance = self.get_object()
        form = UserForm(
            self.request.POST or None,
            instance=instance,
        )
        return form

    def get_success_url(self):
        return reverse_lazy(
            'billboard:profile',
            kwargs={
                'username': self.kwargs['username'],
            }
        )


class CommentCreate(CreateView):
    model = Comment
    template_name = 'billboard/detail.html'

    def get_success_url(self):
        return reverse_lazy(
            'billboard:billboard_detail',
            kwargs={
                'pk': self.kwargs['pk'],
            }
        )

    def get_form(self, form_class=CommentForm):
        form = CommentForm(
            self.request.POST or None
        )
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.billboard_id = self.kwargs['pk']
        form.save()
        return super().form_valid(form)


class CommentUpdate(UpdateView):
    model = Comment
    template_name = 'billboard/comment.html'

    def get_object(self, queryset=Comment.objects.all()):
        comment = queryset.get(
            pk=self.kwargs['comment_id']
        )
        return comment

    def get_form(self, form_class=CommentForm):
        comment_id = self.kwargs['comment_id']
        instance = Comment.objects.get(
            pk=comment_id,
        )
        form = CommentForm(
            self.request.POST or None,
            instance=instance,
        )
        return form

    def get_success_url(self):
        return reverse_lazy(
            'billboard:billboard_detail',
            kwargs={
                'pk': self.kwargs['pk'],
            },
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class CommentDelete(DeleteView):
    model = Comment
    template_name = 'billboard/comment.html'

    def get_object(self, queryset=Comment.objects.all()):
        comment = queryset.get(
            pk=self.kwargs['comment_id']
        )
        return comment

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def get_success_url(self):
        return reverse_lazy(
            'billboard:billboard_detail',
            kwargs={
                'pk': self.kwargs['pk']
            }
        )

sample_site/templates/billboard/category.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
{{ category.title }} :: Доска объявлений
{% endblock title %}

{% block header_name %}
<h1>Объявления в категории "{{ category.title }}" </h1>
{% endblock header_name %}

{% block content %}
<div>
  <h2> Описание категории "{{ category.title }}" </h2>
  <p>{{ category.description }} </p>
  <hr>
  <hr>
</div>
{% for billboard in page_obj %}
<div>
  <hr>
  <h2>{{ billboard.title }}</h2>
  <p>
    Категория:
    <a href="{% url 'billboard:category_bbs' billboard.category.slug %}"
        >{{ billboard.category.title }}</a
        >
      </p>
      <p>Опубликовано: {{ billboard.published_at|date:"d.m.Y H:i:s" }}</p>
      <a href="{% url "billboard:billboard_detail" billboard.id %}">Подробнее</a>
      <hr>
</div>
{% endfor %}
{% include "includes/paginator.html" %}
{% endblock content %}

sample_site/templates/billboard/comment.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
{% if '/edit_comment/' in request.path %}
Редактирования комментария
{% else %}
Удаление комментария
{% endif %}
{% endblock title %}

{% block header_name %}
{% if '/edit_comment/' in request.path %}
<h1>Редактирование комментария</h1>
{% else %}
<h1>Удаление комментария</h1>
{% endif %}
{% endblock header_name %}


{% block content %}
<div  class="col d-flex justify-content-center">
    <form method="post"
    {% if '/edit_comment/' in request.path %}
    action="{% url 'billboard:update_comment' comment.billboard_id comment.id %}"
    {% endif %}>
    {% csrf_token %}
    {% if not '/delete_comment/' in request.path %}
    <div class="col d-flex justify-content-center">
        <div class="card" style="width: 40rem;">
            <div class="card-body">
                {% bootstrap_form form %}
            </div>        
        </div>
    </div>
    {% else %}
    <div class="col d-flex justify-content-center">
        <div class="card" style="width: 40rem;">
            <div class="card-body">
                <p>ID: <b>{{ comment.id }}</b></p>
                <p><b>Текст комментария:</b> {{ comment.text }}</p>
            </div>        
        </div>
    </div>
    {% endif %}
    {% bootstrap_button content='Отправить' button_type='submit' %}
    </form>
</div>
{% endblock content %}

sample_site/templates/billboard/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
{% if '/create/' in request.path %}
Добавление объявления
{% elif '/edit/' in request.path %}
Изменение объявления
{% else %}
Удаление объявления
{% endif %}
{% endblock title %}

{% block header_name %}
{% if '/create/' in request.path %}
<h1>Добавление объявления</h1>
{% elif '/edit/' in request.path %}
<h1>Изменение объявления</h1>
{% else %}
<h1>Удаление объявления</h1>
{% endif %}
{% endblock header_name %}
{% block content %}
<div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
          <div class="card-body">
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% if not '/delete/' in request.path %}
                <table>
                    {% bootstrap_form form %}
                </table>
                {% else %}
                <article>
                    <h1>Удалить объявления {{ billboard.title }}?</h1>
                    <div>
                        <p><b>Название:</b> {{ billboard.title }}</p>
                        <p><b>Описание:</b> {{ billboard.content }}</p>
                        <p><b>Цена:</b> {{ billboard.price }}</p>
                    </div>  
                </article>
                {% endif %}
                <input type="submit" value="Отправить">
            </form>
        </div>
    </div>
</div>
{% endblock content %}

sample_site/templates/billboard/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
Объявление {{ billboard.id }}
{% endblock title %}

{% block header_name %}
<h1>Объявление {{ billboard.id }}</h1>
{% endblock header_name %}

{% block content %}
{% include "includes/billboard_card.html" %}
{% if user == billboard.author %}
<div class="col d-flex justify-content-center">
  <p>
    <a href="{% url "billboard:update_billboard" billboard.id %}" class="card-link">Редактировать объявление</a>
    <a href="{% url "billboard:delete_billboard" billboard.id %}" class="card-link text-muted">Удалить объявление</a></p>
</div>
{% endif %}
<hr>
{% include "includes/comments.html" %}
{% endblock content %}

sample_site/templates/billboard/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}
Доска объявлений
{% endblock title %}

{% block header_name %}
<h1>Объявления</h1>
{% endblock header_name %}

{% block content %}
{% for billboard in page_obj %}
<div>
  <hr>
  <h2>{{ billboard.title }}</h2>
  <p>Автор: <a href="{% url "billboard:profile" billboard.author.username %}">@{{ billboard.author.username }}</a></p>
  <p>
    Категория:
    <a href="{% url 'billboard:category_bbs' billboard.category.slug %}"
    >{{ billboard.category.title }}</a
    >
  </p>
  <p>Опубликовано: {{ billboard.published_at|date:"d.m.Y H:i:s" }}</p>
  <p>Цена: {{ billboard.price }} руб.</p>
  <a href="{% url "billboard:billboard_detail" billboard.id %}">Подробнее</a>
  <hr>
</div>
{% endfor %}
<span>
  <h2>
    Фильтры
  </h2>
  <form method="post">
    {% csrf_token %}
    <table>
      {% bootstrap_form form %}
    </table>
    <p><input type="submit" value="Применить фильтры"/></p>
    <form> 
</span>
<div>
  {% include "includes/paginator.html" %}
</div>
{% endblock content %}

sample_site/templates/billboard/profile.html
{% extends "base.html" %} {% load django_bootstrap5 %} {% block title %} Профиль
{% endblock title %} {% block header_name %}
<h1>Профиль {{ profile.username }}</h1>
{% endblock header_name %} {% block content %}
<h1 class="mb-5 text-center">Страница пользователя {{ profile.username }}</h1>
<small>
  <ul class="list-group list-group-horizontal justify-content-center mb-3">
    <li class="list-group-item text-muted">
      Имя пользователя: {% if profile.get_full_name %}{{ profile.get_full_name }}{% else %}не указано{% endif %}
    </li>
    <li class="list-group-item text-muted">
      Регистрация: {{ profile.date_joined }}
    </li>
    <li class="list-group-item text-muted">
      Роль: {% if profile.is_staff %}Админ{% else %}Пользователь{% endif %}
    </li>
  </ul>
  <ul class="list-group list-group-horizontal justify-content-center">
    {% if user.is_authenticated and request.user == profile %}

    <a class="btn btn-sm text-muted" href="{% url 'password_change' %}"
      >Изменить пароль</a
    >
    <a
      class="btn btn-sm text-muted"
      href="{% url 'billboard:edit_profile' profile.username %}"
      >Изменить профиль</a
    >
    {% endif %}
  </ul>
</small>

<div>
  {% for billboard in billboards %}
  <article class="mb-5">
    {% include "includes/billboard_card.html" %}
  </article>
  {% endfor %}
</div>
{% endblock content %}

sample_site/templates/billboard/user.html
{% extends "base.html" %}

{% load django_bootstrap5 %}

{% block title %}
Редактирование {{ user.username }}
{% endblock title %}

{% block header_name %}
<h1>Редактирование профиля {{ user.username }}</h1>
{% endblock header_name %}

{% block content %}
<div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
        <div class="card-header">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %} {% bootstrap_form form %} 
                    {% bootstrap_button button_type="submit" content="Отправить" %}
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}